### ISSUE TITLE
 Problemas de Configuração e Dependências Ausentes

### ISSUE THREAD

**Issue by ParaFoxy-xto** [mascarenhasav/AbCD#2]
Olá equipe,

Estou enfrentando alguns problemas ao executar o projeto, e gostaria da ajuda da comunidade para resolvê-los. Abaixo estão os detalhes dos problemas encontrados:

1. Erro com o Módulo 'numpy':
Ao executar o projeto, ocorre um erro relacionado à ausência do módulo 'numpy'. Certifiquei-me de que o NumPy não está instalado, e ao tentar instalar usando pip install numpy, o problema persiste.

2. Erros ao Tentar Importar Módulos em Arquivos de Métricas:
Existem erros relacionados à importação de módulos em arquivos de métricas específicos (offlineError.py e bestBeforeChange.py). Ambos os arquivos parecem não encontrar o módulo 'numpy'. Como posso resolver esse problema?

3. Problema com o Arquivo config.ini:
Ao executar o projeto, é gerada uma exceção FileNotFoundError ao tentar abrir o arquivo config.ini. Certifiquei-me de que o arquivo está no diretório especificado, mas o problema persiste.

Mensagem de Erro Adicional:
Além disso, ocasionalmente, o projeto falha com o erro:

> Traceback (most recent call last):
  File "d:\downloads\AbCD-main\AbCD-main\abcd\abcd.py", line 598, in <module>
    main()
  File "d:\downloads\AbCD-main\AbCD-main\abcd\abcd.py", line 555, in main
    with open(f"{path}/config.ini") as f:
FileNotFoundError: [Errno 2] No such file or directory: './config.ini'

Ambiente de Execução:
Sistema Operacional: Windows 11
Versão do Python: Pyrhon 3.11.6

Durante  a última reunião na sexta o @caldeiratalles falou que algo similar aconteceu com ele, era um problema de configuração do ambiente, creio eu que meu ambiente está configurado corretamente, mas ainda sim vou dar uma olhada e incremento nessa issue. 
Também foi apontado junto ao professor Klaus o uso de separadores de diretórios em sistemas baseados em Unix/Linux. Vi que utiliza a biblioteca "os" para a maioria dos casos, mas nesta linha não, que é onde vem o erro, é algo intencionado?

**Comment by mascarenhasav** [comment]
Ola @ParaFoxy-xto, valew pela mensagem!

Pela descricao dos erros que voce fez, como por exemplo nao achar o modulo numpy mesmo voce tendo o instalado, eu diria que tem chances sim de ser problema de configuracao de ambiente, o python eh meio enjoado com isso as vezes, e se por exemplo, voce tiver mais de uma versao do python instalado na maquina, tem que estar seguro de qual eh a versao que esta como padrao, pois eh essa que eh utilizada quando voce tenta rodar um comando python. 

A solucao que eu prefiro para evitar este tipo de problema eh sempre utilizar [pyenv](https://pyenv-win.github.io/pyenv-win/), e virutal environment. Caso nao esteja familiarizado com essas ferramentas ainda, achei esses dois guias aqui em portugues: [pyenv](https://blog.accurate.com.br/tutorial-pyenv/) e [venv](https://docs.python.org/pt-br/3/library/venv.html). Pode parecer um pouco complicado no comeco, mas basicamente o que essas ferramentas permitem eh que voce tenha controle da exata versao do python que voce quer usar e tambem separa-las por projeto. Se tiver qualquer duvida em relacao ao uso delas, pode perguntar sem problemas inclusive.

Bom, dito isso, o que eu recomendo, e foi o que tambem recomendei ao @caldeiratalles, eh que se possivel, passasse a utilizar a nova versao do framework, que esta bem mais completa, e eh a qual eu estou trabalhando no momento, o link eh esse aqui [AbEC](https://abec-ec.github.io/). No site tem uma descricao um pouco melhor sobre como utlizar o framework com um passo a passo, inclusive seria de grande ajuda o uso dele, para que possamos ir solucionando os possiveis problemas que ainda vao ter rsrs.

Aaah, um detalhe eh que nessa nova versao no framework eu faco uso de virtual environment, para que (teoricamente) diminua estes problemas com dependencias de modulos python.

Se tiver qualquer outra duvida, fique a vontade para pergunta!

Valeww!
